# Generated by Django 4.1.2 on 2022-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist", name="Age", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="artist",
            name="First_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="artist",
            name="Last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lyric", name="content", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="song", name="title", field=models.CharField(max_length=100),
        ),
    ]
